package:
  name: openocd
  version: 0.10.0.git

source:
  git_tag: master
  git_url: git://github.com/ntfreak/openocd

build:
  number: 0

test:
  commands:
    - openocd -v
    - openocd -v 2>&1 | head -1 | grep -q -v dirty
    - openocd -v 2>&1 | head -1 | grep -q -- "-[0-9][0-9][0-9][0-9][0-9]-[0-9a-z]\+ "

requirements:
  build:
    - system # [linux]
    - libusb >=1.0.16
  run:
    - libusb >=1.0.16

about:
  home: http://openocd.org/
  license: GPLv2+
  summary: 'OpenOCD provides on-chip programming and debugging support with a layered architecture of JTAG interface and TAP support'
